# Generated by Django 3.1.1 on 2020-10-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specification',
            field=models.JSONField(default=dict),
        ),
    ]
