# Generated by Django 3.1.1 on 2020-10-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20201012_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specification',
            field=models.JSONField(),
        ),
    ]
