# Generated by Django 3.1.1 on 2020-10-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201012_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cpu',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='gpu',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='os',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='ram',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='screen',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='storage',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
