# Generated by Django 3.1.1 on 2020-10-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20201012_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='specification',
        ),
    ]
