# Generated by Django 3.1.1 on 2020-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20201012_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='cpu',
            field=models.CharField(blank=True, max_length=83),
        ),
        migrations.AlterField(
            model_name='products',
            name='gpu',
            field=models.CharField(blank=True, max_length=83),
        ),
        migrations.AlterField(
            model_name='products',
            name='ram',
            field=models.CharField(blank=True, max_length=67),
        ),
        migrations.AlterField(
            model_name='products',
            name='screen',
            field=models.CharField(blank=True, max_length=105),
        ),
        migrations.AlterField(
            model_name='products',
            name='storage',
            field=models.CharField(blank=True, max_length=83),
        ),
    ]
