# Generated by Django 3.1.1 on 2020-10-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20201014_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='typpe',
            field=models.CharField(blank=True, choices=[('lp', 'laptop'), ('pc', 'pc case'), ('special', 'special line')], max_length=20),
        ),
    ]
