# Generated by Django 3.1.1 on 2020-10-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_products_typpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
