# Generated by Django 3.1.1 on 2020-11-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_products_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='products',
            name='os',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='products',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='products',
            name='storage',
        ),
    ]
