# Generated by Django 3.1.1 on 2020-11-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20201113_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.JSONField(default={}),
        ),
    ]
