# Generated by Django 3.1.1 on 2020-11-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20201113_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acounter',
            name='favourites',
        ),
        migrations.AddField(
            model_name='acounter',
            name='user_rating',
            field=models.JSONField(default={}),
        ),
    ]
