# Generated by Django 3.1.1 on 2020-11-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20201113_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acounter',
            name='user_rating',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
